steps:
  - name: goreleaser
    when:
      branch: main
      event: tag
    image: goreleaser/goreleaser
    commands:
      - goreleaser release --cleans -f ./cmd/.goreleaser.yaml
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    depends_on: [ test ]
