steps:
  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token: 
        from_secret: bot_token
      to: 
        from_secret: telegram_user
depends_on:
  - test
  - release

runs_on: [ success, failure ]
