steps:
  - name: notify
    when:
      status: [ success, failure ]
    image: appleboy/drone-telegram
    settings:
      token: 
        from_secret: bot_token
      to: 
        from_secret: telegram_user
depends_on: [ test, goreleaser ]
