steps:
  - name: test
    when:
      event: push
    image: cgr.dev/chainguard/go:latest
    commands:
      - export PATH=$PATH:/root/go/bin
      - make test
  - name: goreleaser
    when:
      branch: main
      event: tag
    image: goreleaser/goreleaser
    commands:
      - goreleaser release --cleans -f ./cmd/.goreleaser.yaml
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    depends_on: [ test ]
  - name: notify
    when:
      status: [ success, failure ]
    image: appleboy/drone-telegram
    settings:
      token: 
        from_secret: bot_token
      to: 
        from_secret: telegram_user
    depends_on: [ test, goreleaser ]
