steps:
  - name: test
    when:
      event: push
    image: cgr.dev/chainguard/go:latest
    commands:
      - export PATH=$PATH:/root/go/bin
      - make test
  - name: failure
    when:
      event: push
    image: ubuntu
    commands:
      - exit 1
  - name: test notification
    when:
      - status: [ failure ]
    image: appleboy/drone-telegram
    settings:
      token: 
        from_secret: bot_token
      to: 
        from_secret: telegram_user
      message: >
         build {{build.link}} ${CI_PREV_PIPELINE_STATUS}. 
