steps:
  - name: test
    when:
      event: push
    image: cgr.dev/chainguard/go:latest
    commands:
      - export PATH=$PATH:/root/go/bin
      - make test
  - name: send telegram notification
    when:
      event: push
    image: appleboy/drone-telegram
    environment:
      PLUGIN_TOKEN: 
        from_secret: bot_token
      PLUGIN_TO: 
        from_secret: telegram_user
      PLUGIN_MESSAGE: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
