steps:
  - name: test
    when:
      event: push
    image: cgr.dev/chainguard/go:latest
    commands:
      - export PATH=$PATH:/root/go/bin
      - make test
  - name: fail
    image: ubuntu
    commands:
      - exit 1
  - name: test notification
    when:
      - status: [ success, failure ]
    image: appleboy/drone-telegram
    settings:
      token: 
        from_secret: bot_token
      to: 
        from_secret: telegram_user
      format: Markdown
      message: >
        Build {{build.number}} of {{repo.name}} finished with a status of {{build.status}}.
        Commit by {{commit.author}} on {{commit.branch}}:
        ``` {{commit.message}} ```
        {{build.link}}
